In [1]:
import numpy as np

In [2]:
X_train = np.array([[2104, 5, 1, 45], [1416, 3, 2, 40], [852, 2, 1, 35]])
Y_train = np.array([460, 232, 178])

In [3]:
print(X_train[0])

[2104    5    1   45]


In [4]:
print(X_train.shape)
print(Y_train.shape)

(3, 4)
(3,)


In [5]:
b_init = 785.1811367994083
w_init = np.array([0.39133535, 18.75376741, -53.36032453, -26.42131618])

In [6]:
print(w_init.shape)

(4,)


In [7]:
def predict(x, w, b):
    n = x.shape[0]
    p = 0
    for i in range(n):
        p += x[i] * w[i]
    p += b
    return p 

In [17]:
x_vec = X_train[2, :]
print(x_vec.shape)

# Make prediction
print(predict(x_vec, w_init, b_init))

(4,)
177.99999898940814


In [9]:
def predict_vectorized(x, w, b):
    p = np.dot(x, w) + b
    return p

In [10]:
print(predict_vectorized(x_vec, w_init, b_init))
print(predict_vectorized(X_train, w_init, b_init))

177.99999898940814
[459.99999762 231.99999837 177.99999899]


In [11]:
def compute_cost(X, y, w, b):
    """
    Args:
        X (ndarray (m, n)): Data, m example with n features
        y (ndarray (m,)): Target values
        w (ndarray(n,)): model weights
        b (scalar): model bias
    """
    m = X.shape[0]

    cost = 0
    for i in range(m):
        cost += (predict_vectorized(X[i], w, b) - y[i]) ** 2

    return cost / (2 * m)

In [12]:
print(compute_cost(X_train, Y_train, w_init, b_init))

1.5578904428966628e-12


In [13]:
def compute_cost_vect(X, y, w, b):
    m = X.shape[0]
    
    cost = np.sum((predict_vectorized(X, w, b) - y) ** 2)
    return cost / (2*m)

In [14]:
print(compute_cost_vect(X_train, Y_train, w_init, b_init))

1.5578904045996674e-12


In [18]:
def compute_gradient(X, y, w, b):
    m, n = np.shape(X)
    dj_dw = np.zeros(n)
    dj_db = 0.

    for i in range(m):
        err = predict(X[i], w, b) - y[i]
        for j in range(n):
            dj_dw[j] += err * X[i][j]
        dj_db += err

    dj_dw /= m
    dj_db /=m
    return dj_dw, dj_db
        

In [19]:
dj_dw, dj_db = compute_gradient(X_train, Y_train, w_init, b_init)
print(dj_dw)
print(dj_db)

[-2.72623577e-03 -6.27197263e-06 -2.21745578e-06 -6.92403391e-05]
-1.6739251501955248e-06


In [29]:
import copy, math

def gradient_descent(X, y, w_init, b_init, alpha, num_iters):
    w = copy.deepcopy(w_init)
    b = b_init

    for i in range(num_iters):
        dj_dw, dj_db = compute_gradient(X, y, w, b)
        
        w -= alpha * dj_dw
        b -= alpha * dj_db

        if i % 1000 == 0:
            cost = compute_cost_vect(X, y, w, b)
            print(f"Iteration: {i:4d}, Cost: {cost:8.2f}")
    return w, b

In [43]:
init_w = np.zeros_like(w_init)
init_b = 0.
iterations = 10000
alpha = 5.0e-7

w_final, b_final = gradient_descent(X_train, Y_train, init_w, init_b, alpha, iterations)

Iteration:    0, Cost:  2529.46
Iteration: 1000, Cost:   686.69
Iteration: 2000, Cost:   677.19
Iteration: 3000, Cost:   668.48
Iteration: 4000, Cost:   660.50
Iteration: 5000, Cost:   653.19
Iteration: 6000, Cost:   646.49
Iteration: 7000, Cost:   640.35
Iteration: 8000, Cost:   634.72
Iteration: 9000, Cost:   629.56


In [23]:
w_final

array([ 0.21699899,  0.03240792, -0.10755879, -0.5799772 ])

In [24]:
b_final

np.float64(-0.019077710470483206)

In [44]:
m = X_train.shape[0]

for i in range(m):
    prediction = predict(X_train[i], w_final, b_final)
    print(f"Actual label: {Y_train[i]}, Prediction: {prediction}")

Actual label: 460, Prediction: 430.50230063959395
Actual label: 232, Prediction: 283.9345079675299
Actual label: 178, Prediction: 164.52211536512178


In [45]:
def zscore_normalize_features(X):
    mu = np.mean(X, axis=0)
    sigma = np.std(X, axis=0)
    
    X_norm = (X - mu) / sigma

    return X_norm

In [46]:
X_norm = zscore_normalize_features(X_train)
print(X_norm)

[[ 1.26311506  1.33630621 -0.70710678  1.22474487]
 [-0.08073519 -0.26726124  1.41421356  0.        ]
 [-1.18237987 -1.06904497 -0.70710678 -1.22474487]]


In [38]:
init_w = np.zeros_like(w_init)
init_b = 0.
iterations = 10000
alpha = 5.0e-4

w_final, b_final = gradient_descent(X_norm, Y_train, init_w, init_b, alpha, iterations)

Iteration:    0, Cost: 49454.33
Iteration: 1000, Cost: 15933.51
Iteration: 2000, Cost:  5746.77
Iteration: 3000, Cost:  2107.78
Iteration: 4000, Cost:   774.87
Iteration: 5000, Cost:   284.96
Iteration: 6000, Cost:   104.79
Iteration: 7000, Cost:    38.54
Iteration: 8000, Cost:    14.17
Iteration: 9000, Cost:     5.21


In [40]:
m = X_train.shape[0]

for i in range(m):
    prediction = predict(X_norm[i], w_final, b_final)
    print(f"Actual label: {Y_train[i]}, Prediction: {prediction}")

Actual label: 460, Prediction: 457.95441523571753
Actual label: 232, Prediction: 230.2879313778153
Actual label: 178, Prediction: 175.90296487720127
