In [2]:
import numpy as np

In [10]:
a = np.zeros(4)
b = np.zeros((4,))
c = np.random.random_sample(10)

In [12]:
print(a)
print(b)
print(c)
print(c.shape)

[0. 0. 0. 0.]
[0. 0. 0. 0.]
[0.17473603 0.84947107 0.87949067 0.81943614 0.14287423 0.41380366
 0.59232107 0.88690027 0.07595552 0.53731996]
(10,)


In [13]:
a = np.zeros((4,2))
b = np.zeros((2, 4))
c = np.random.random_sample((4, 3))

In [14]:
print(a)
print(b)
print(c)

[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[0.76298041 0.69005005 0.44343866]
 [0.74460939 0.55863138 0.2061812 ]
 [0.35786615 0.32497314 0.10962186]
 [0.10705736 0.19991762 0.93529599]]


In [20]:
a = np.arange(4)
b = np.arange(4.)
c = np.random.rand(4)
d = np.random.rand(4, 2)

In [21]:
print(a)
print(b)
print(c)
print(d)

[0 1 2 3]
[0. 1. 2. 3.]
[0.97534961 0.08466839 0.20248037 0.32496367]
[[0.74772474 0.43597803]
 [0.50768765 0.27379348]
 [0.71283893 0.3892003 ]
 [0.36086511 0.2155365 ]]


In [25]:
a = np.arange(2, 10)
print(a)

[2 3 4 5 6 7 8 9]


In [26]:
a = np.array([1,2,3,4,5])
b = -a
c = np.sum(a)
d = np.mean(a)
e = a ** 2

In [27]:
print(a)
print(b)
print(c)
print(d)
print(e)


[1 2 3 4 5]
[-1 -2 -3 -4 -5]
15
3.0
[ 1  4  9 16 25]


## Vector Operations

In [32]:
X = np.random.rand(4, 3)
w = np.random.rand(3)
print(X)
print(w)
print(np.dot(X, w))

[[0.79658558 0.48694194 0.32353677]
 [0.71818327 0.79391877 0.15038786]
 [0.76356349 0.11068049 0.35785279]
 [0.86993645 0.30972188 0.3294225 ]]
[0.3626532  0.51577981 0.56696297]
[0.72347249 0.75520307 0.53688478 0.66200389]


## Reshape

In [31]:
a = np.arange(8).reshape(-1, 2)
print(a)

[[0 1]
 [2 3]
 [4 5]
 [6 7]]


## Vector 2-D slicing operations

In [37]:
a = np.arange(20).reshape(-1, 10)

print(a[0, 1:8:2])

print(a[:, 0: 9: 3])

print(a[1, :])

[1 3 5 7]
[[ 0  3  6]
 [10 13 16]]
[10 11 12 13 14 15 16 17 18 19]
